# Generated by Django 3.2.4 on 2021-07-08 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeExpenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Consumed', 'Consumed'), ('Wastes', 'Wastes')], default='Consumed', max_length=50)),
                ('quantity', models.FloatField()),
                ('estimated_price', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('expense_of', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200)),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('comment_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_qty', models.FloatField()),
                ('area', models.FloatField()),
                ('production_date', models.DateTimeField(auto_now_add=True)),
                ('farmer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_category', models.CharField(choices=[('False Information', 'False Information'), ('Fake Products', 'Fake Products'), ('Misinformation', 'Misinformation'), ('Something Else', 'Something Else')], default='Misinformation', max_length=50)),
                ('report_description', models.CharField(max_length=200)),
                ('reported_date', models.DateTimeField(auto_now_add=True)),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=100)),
                ('prod_category', models.CharField(choices=[('Cereals', 'Cereals'), ('Pulses', 'Pulses'), ('Vegetables', 'Vegetables'), ('Fruits', 'Fruits'), ('Nuts', 'Nuts'), ('Oilseeds', 'Oilseeds'), ('Sugars and Starches', 'Sugars and Starches'), ('Fibres', 'Fibres'), ('Beverages', 'Beverages'), ('Narcotics', 'Narcotics'), ('Spices', 'Spices'), ('Condiments', 'Condiments'), ('Others', 'Others')], default='Cereals', max_length=25)),
                ('prod_img', models.ImageField(null=True, upload_to='static/product_images')),
                ('product_home_expense', models.ManyToManyField(related_name='product_home_expense', through='farmers.HomeExpenses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductsForSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_in_kg', models.FloatField()),
                ('price_per_kg', models.FloatField()),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('details', models.CharField(max_length=250, null=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farmers.products')),
                ('product_comments', models.ManyToManyField(related_name='product_comments', through='farmers.ProductComment', to=settings.AUTH_USER_MODEL)),
                ('product_reports', models.ManyToManyField(related_name='product_reports', through='farmers.ProductReport', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.FloatField()),
                ('farmer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farmers.products')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_sold', models.FloatField()),
                ('sold_price', models.FloatField()),
                ('sold_date', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.CharField(max_length=1250, null=True)),
                ('sold_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farmer_id', to=settings.AUTH_USER_MODEL)),
                ('sold_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='farmers.productsforsale')),
                ('sold_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='products_for_sales',
            field=models.ManyToManyField(related_name='products_for_sale', through='farmers.ProductsForSale', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='products',
            name='products_production',
            field=models.ManyToManyField(related_name='products_production', through='farmers.Production', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='products',
            name='products_stock',
            field=models.ManyToManyField(related_name='products_stock', through='farmers.ProductStock', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productreport',
            name='reported_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farmers.productsforsale'),
        ),
        migrations.AddField(
            model_name='production',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='farmers.products'),
        ),
        migrations.AddField(
            model_name='productcomment',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farmers.productsforsale'),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='homeexpenses',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='farmers.products'),
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particular', models.CharField(max_length=75)),
                ('category', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('expense_date', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.CharField(max_length=150, null=True)),
                ('expense_of', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
