# Generated by Django 3.1.6 on 2021-06-27 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='prod_added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prod_added_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProductReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_category', models.CharField(choices=[('False Information', 'False Information'), ('Fake Products', 'Fake Products'), ('Misinformation', 'Misinformation'), ('Something Else', 'Something Else')], default='Misinformation', max_length=50)),
                ('report_description', models.CharField(max_length=200)),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reported_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farmers.products')),
            ],
        ),
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200)),
                ('comment_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('comment_on', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farmers.products')),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='comments',
            field=models.ManyToManyField(related_name='comments', through='farmers.ProductComment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='products',
            name='reports',
            field=models.ManyToManyField(related_name='reports', through='farmers.ProductReport', to=settings.AUTH_USER_MODEL),
        ),
    ]
