# Generated by Django 3.1.6 on 2021-06-27 15:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0002_auto_20210627_2049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcomment',
            old_name='comment_on',
            new_name='product',
        ),
        migrations.AddField(
            model_name='productcomment',
            name='comment_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productreport',
            name='reported_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
