# Generated by Django 3.1.6 on 2021-07-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0003_auto_20210627_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='prod_img',
            field=models.ImageField(null=True, upload_to='static/product_images'),
        ),
    ]
