# Generated by Django 3.1.6 on 2021-07-04 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0004_products_prod_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreport',
            name='reported_by',
        ),
        migrations.RemoveField(
            model_name='productreport',
            name='reported_product',
        ),
        migrations.RemoveField(
            model_name='products',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='products',
            name='reports',
        ),
        migrations.DeleteModel(
            name='ProductComment',
        ),
        migrations.DeleteModel(
            name='ProductReport',
        ),
    ]
