# Generated by Django 3.1.6 on 2021-07-05 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0006_auto_20210705_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsold',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='farmers.productsforsale'),
        ),
    ]
