# Generated by Django 3.1.6 on 2021-07-05 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0007_auto_20210705_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsold',
            old_name='farmer_id',
            new_name='sold_by',
        ),
        migrations.RenameField(
            model_name='productsold',
            old_name='product_id',
            new_name='sold_product',
        ),
        migrations.RenameField(
            model_name='productsold',
            old_name='buyer_id',
            new_name='sold_to',
        ),
    ]
