# Generated by Django 3.1.6 on 2021-07-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0008_auto_20210705_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='prod_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
