# Generated by Django 3.1.6 on 2021-07-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0009_auto_20210705_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsold',
            name='remarls',
            field=models.CharField(max_length=1250, null=True),
        ),
    ]
