# Generated by Django 3.1.6 on 2021-07-07 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0010_productsold_remarls'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsold',
            old_name='remarls',
            new_name='remarks',
        ),
    ]
