# Generated by Django 3.1.6 on 2021-07-07 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farmers', '0011_auto_20210707_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsforsale',
            name='details',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particular', models.CharField(max_length=75)),
                ('category', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('expense_date', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.CharField(max_length=150, null=True)),
                ('expense_of', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
