# Generated by Django 3.1.6 on 2021-07-08 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farmers', '0013_homeexpenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeexpenses',
            name='expense_of',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
