# Generated by Django 3.1.6 on 2021-07-08 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farmers', '0014_homeexpenses_expense_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeexpenses',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='farmers.products'),
        ),
        migrations.AddField(
            model_name='products',
            name='product_home_expense',
            field=models.ManyToManyField(related_name='product_home_expense', through='farmers.HomeExpenses', to=settings.AUTH_USER_MODEL),
        ),
    ]
