# Generated by Django 3.1.6 on 2021-07-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0016_auto_20210708_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='category',
        ),
        migrations.AddField(
            model_name='expenses',
            name='expense_type',
            field=models.CharField(choices=[('Before Harvesting', 'Before Harvesting'), ('During Harvesting', 'During Harvesting'), ('After Harvesting', 'After Harvesting')], default='Before Harvesting', max_length=50),
        ),
        migrations.AddField(
            model_name='expenses',
            name='quantity',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expenses',
            name='unit',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homeexpenses',
            name='remarks',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='production',
            name='remarks',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
