# Generated by Django 3.1.6 on 2021-07-08 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0017_auto_20210708_2208'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expenses',
        ),
    ]
