# Generated by Django 3.1.6 on 2021-07-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0020_auto_20210712_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsold',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
