# Generated by Django 3.1.6 on 2021-08-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0024_productsforsale_to_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='remarks',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='homeexpenses',
            name='remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
