# Generated by Django 3.1 on 2021-09-11 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0026_auto_20210813_2240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagetest',
            old_name='reccomended_crops',
            new_name='recomended_crops',
        ),
        migrations.RenameField(
            model_name='npktest',
            old_name='reccommended_crop',
            new_name='recommended_crop',
        ),
    ]
