# Generated by Django 3.1.6 on 2021-06-26 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('modal', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('available_For_Rent', models.BooleanField()),
                ('available_To_Buy', models.BooleanField()),
                ('price_To_Buy', models.IntegerField()),
                ('price_To_Rent', models.IntegerField()),
                ('details', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
