# Generated by Django 3.1.6 on 2021-06-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='available_For_Rent',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='available_To_Buy',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='price_To_Buy',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='price_To_Rent',
            field=models.FloatField(),
        ),
    ]
