# Generated by Django 3.1.6 on 2021-07-01 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210626_1704'),
        ('api', '0006_auto_20210626_2207'),
    ]

    operations = [
    ]
