# Generated by Django 3.1.6 on 2021-07-01 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_merge_20210701_2118'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Equipment',
        ),
    ]
