# Generated by Django 3.1.6 on 2021-08-24 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0014_reportuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportuser',
            name='reported_profile',
        ),
        migrations.AddField(
            model_name='reportuser',
            name='reported_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reported_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
