# Generated by Django 3.1 on 2021-09-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20210824_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('feedback_type', models.CharField(choices=[('Comments', 'Comments'), ('Bug Reports', 'Bug Reports'), ('Questions', 'Questions')], max_length=20)),
            ],
        ),
    ]
