# Generated by Django 3.1 on 2021-09-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='description',
            field=models.TextField(default='Description'),
            preserve_default=False,
        ),
    ]
