# Generated by Django 3.1.6 on 2021-07-01 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='available_For_Rent',
            new_name='available_for_rent',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='available_To_Buy',
            new_name='available_to_buy',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='price_To_Buy',
            new_name='price_yo_buy',
        ),
    ]
