# Generated by Django 3.1.6 on 2021-07-01 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_auto_20210701_2125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='price_To_Rent',
            new_name='price_to_buy',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='price_yo_buy',
            new_name='price_to_rent',
        ),
    ]
