# Generated by Django 3.1.6 on 2021-07-07 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_auto_20210707_2039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipmenttodisplay',
            old_name='Duration',
            new_name='duration',
        ),
    ]
