# Generated by Django 3.1.6 on 2021-07-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0007_auto_20210707_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmenttodisplay',
            name='available_for_rent',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='equipmenttodisplay',
            name='available_to_buy',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
