# Generated by Django 3.1.6 on 2021-07-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0008_auto_20210707_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='buydetails',
            name='delivered_address',
            field=models.CharField(default='ktm', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentdetails',
            name='delivered_address',
            field=models.CharField(default='ktm', max_length=100),
            preserve_default=False,
        ),
    ]
