# Generated by Django 3.1.6 on 2021-07-28 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0009_auto_20210728_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buydetails',
            name='sold_by',
        ),
        migrations.RemoveField(
            model_name='rentdetails',
            name='rented_by',
        ),
    ]
