# Generated by Django 3.1.6 on 2021-07-31 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0010_auto_20210728_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmenttodisplay',
            name='eqp_img',
            field=models.CharField(max_length=1200, null=True),
        ),
    ]
