# Generated by Django 3.1.6 on 2021-08-07 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0012_auto_20210807_1259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipmentcomment',
            old_name='product',
            new_name='equipment',
        ),
    ]
