# Generated by Django 3.1.6 on 2021-08-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0013_auto_20210807_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmenttodisplay',
            name='eqp_img',
            field=models.CharField(default='static/eqp_images/no_image.png', max_length=1200, null=True),
        ),
    ]
