# Generated by Django 3.1.6 on 2021-08-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0014_auto_20210807_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmenttodisplay',
            name='to_display',
            field=models.BooleanField(default=True),
        ),
    ]
