# Generated by Django 3.1.6 on 2021-08-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0016_auto_20210809_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buydetails',
            name='remarks',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='equipmenttodisplay',
            name='details',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rentdetails',
            name='remarks',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
