# Generated by Django 3.1.6 on 2021-07-04 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200)),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('comment_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_category', models.CharField(choices=[('False Information', 'False Information'), ('Fake Products', 'Fake Products'), ('Misinformation', 'Misinformation'), ('Something Else', 'Something Else')], default='Misinformation', max_length=50)),
                ('report_description', models.CharField(max_length=200)),
                ('reported_date', models.DateTimeField(auto_now_add=True)),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductsForSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_in_kg', models.FloatField()),
                ('price_per_kg', models.FloatField()),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admins.products')),
                ('product_comments', models.ManyToManyField(related_name='product_comments', through='admins.ProductComment', to=settings.AUTH_USER_MODEL)),
                ('product_reports', models.ManyToManyField(related_name='product_reports', through='admins.ProductReport', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='productreport',
            name='reported_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admins.productsforsale'),
        ),
        migrations.AddField(
            model_name='productcomment',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admins.productsforsale'),
        ),
        migrations.AddField(
            model_name='products',
            name='products_for_sales',
            field=models.ManyToManyField(related_name='products_for_sale', through='admins.ProductsForSale', to=settings.AUTH_USER_MODEL),
        ),
    ]
