# Generated by Django 3.1.6 on 2021-07-05 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_auto_20210704_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production',
            name='farmer_id',
        ),
        migrations.RemoveField(
            model_name='production',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='productreport',
            name='reported_by',
        ),
        migrations.RemoveField(
            model_name='productreport',
            name='reported_product',
        ),
        migrations.RemoveField(
            model_name='products',
            name='products_for_sales',
        ),
        migrations.RemoveField(
            model_name='products',
            name='products_production',
        ),
        migrations.RemoveField(
            model_name='products',
            name='products_stock',
        ),
        migrations.RemoveField(
            model_name='productsforsale',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='productsforsale',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productsforsale',
            name='product_comments',
        ),
        migrations.RemoveField(
            model_name='productsforsale',
            name='product_reports',
        ),
        migrations.RemoveField(
            model_name='productsold',
            name='buyer_id',
        ),
        migrations.RemoveField(
            model_name='productsold',
            name='farmer_id',
        ),
        migrations.RemoveField(
            model_name='productsold',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='productstock',
            name='farmer_id',
        ),
        migrations.RemoveField(
            model_name='productstock',
            name='product_id',
        ),
        migrations.DeleteModel(
            name='ProductComment',
        ),
        migrations.DeleteModel(
            name='Production',
        ),
        migrations.DeleteModel(
            name='ProductReport',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.DeleteModel(
            name='ProductsForSale',
        ),
        migrations.DeleteModel(
            name='ProductSold',
        ),
        migrations.DeleteModel(
            name='ProductStock',
        ),
    ]
